env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: '18.2'
plugins:
  - react
  - react-hooks
  - import
  - jsdoc
  - unicorn
  - '@typescript-eslint'
rules: {
  no-empty: off,
  "@typescript-eslint/no-inferrable-types": off,
  "@typescript-eslint/no-unused-vars": [2, { args: "none" }],
  "@typescript-eslint/no-empty-function": off,
  "no-console": ["error", { allow: ["warn", "error"] }],
}

