/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/no-require-imports */
import { IResponse } from "./models/api/IResponse";
import { IRoute } from "./models/app/IRoute";

export const routes: IRoute[] = [
    {
        path: "/",
        method: "get",
        inline: async () => {
            const packageJson = require("../package.json");
            return {
                name: packageJson.name,
                version: packageJson.version,
            } as IResponse;
        },
    },
    // Generic
    { path: "/init", method: "get", func: "init" },
    { path: "/networks", method: "get", folder: "networks", func: "get" },
    { path: "/node-info/:network", method: "get", folder: "node", func: "info" },
    { path: "/currencies", method: "get", folder: "currency", func: "get", sign: true },
    { path: "/stats/:network", method: "get", folder: "stats", func: "get", sign: true },
    // Legacy
    { path: "/milestones/:network/:milestoneIndex", method: "get", folder: "legacy/milestones", func: "get" },
    { path: "/transactions/:network/:hash", method: "get", folder: "legacy/transactions", func: "get" },
    { path: "/trytes/:network", method: "post", folder: "legacy/trytes", func: "post" },
    { path: "/address/:network/:address", method: "get", folder: "legacy/address", func: "get" },
    // Chrysalis
    { path: "/search/:network/:query", method: "get", folder: "chrysalis", func: "search" },
    { path: "/message/:network/:messageId", method: "get", folder: "chrysalis/message", func: "get" },
    { path: "/milestone/:network/:milestoneIndex", method: "get", folder: "chrysalis/milestone", func: "get" },
    { path: "/output/:network/:outputId", method: "get", folder: "chrysalis/output", func: "get" },
    {
        path: "/transactionhistory/:network/:address",
        method: "get",
        folder: "chrysalis/transactionhistory",
        func: "get",
    },
    {
        path: "/transactionhistory/download/:network/:address",
        method: "post",
        folder: "chrysalis/transactionhistory/download",
        func: "post",
        dataBody: true,
        dataResponse: true,
    },
    {
        path: "/chrysalis/did/:network/:did/document",
        method: "get",
        folder: "/chrysalis/identity/resolution",
        func: "get",
    },
    {
        path: "/chrysalis/did/:network/:did/history",
        method: "get",
        folder: "/chrysalis/identity/history",
        func: "get",
    },
    {
        path: "/chrysalis/did/:network/diffHistory/:integrationMsgId",
        method: "post",
        folder: "/chrysalis/identity/diff",
        func: "get",
        dataBody: true,
    },
    // Stardust
    { path: "/stardust/search/:network/:query", method: "get", folder: "stardust", func: "search" },
    {
        path: "/stardust/balance/:network/:address",
        method: "get",
        folder: "stardust/address/balance",
        func: "get",
    },
    {
        path: "/stardust/balance/chronicle/:network/:address",
        method: "get",
        folder: "stardust/address/balance/chronicle",
        func: "get",
    },
    {
        path: "/stardust/address/outputs/basic/:network/:address",
        method: "get",
        folder: "stardust/address/outputs/basic",
        func: "get",
    },
    {
        path: "/stardust/address/outputs/alias/:network/:address",
        method: "get",
        folder: "stardust/address/outputs/alias",
        func: "get",
    },
    {
        path: "/stardust/address/outputs/nft/:network/:address",
        method: "get",
        folder: "stardust/address/outputs/nft",
        func: "get",
    },
    { path: "/stardust/block/:network/:blockId", method: "get", folder: "stardust/block", func: "get" },
    {
        path: "/stardust/block/metadata/:network/:blockId",
        method: "get",
        folder: "stardust/block/metadata",
        func: "get",
    },
    {
        path: "/stardust/block/children/:network/:blockId",
        method: "get",
        folder: "stardust/block/children",
        func: "get",
    },
    {
        path: "/stardust/milestone/latest/:network",
        method: "get",
        folder: "stardust/milestone/latest",
        func: "get",
    },
    { path: "/stardust/milestone/:network/:milestoneIndex", method: "get", folder: "stardust/milestone", func: "get" },
    {
        path: "/stardust/milestone/blocks/:network/:milestoneId",
        method: "get",
        folder: "stardust/milestone/blocks",
        func: "get",
    },
    {
        path: "/stardust/milestone/stats/:network/:milestoneIndex",
        method: "get",
        folder: "stardust/milestone/influx",
        func: "get",
    },
    { path: "/stardust/output/:network/:outputId", method: "get", folder: "stardust/output", func: "get" },
    {
        path: "/stardust/transaction/:network/:transactionId",
        method: "get",
        folder: "stardust/transaction",
        func: "get",
    },
    {
        path: "/stardust/output/associated/:network/:address",
        method: "post",
        folder: "stardust/output/associated",
        func: "post",
        dataBody: true,
    },
    {
        path: "/stardust/output/tagged/:network/:tag/:outputType",
        method: "get",
        folder: "stardust/output/tagged",
        func: "get",
    },
    {
        path: "/stardust/transactionhistory/:network/:address",
        method: "get",
        folder: "stardust/transactionhistory",
        func: "get",
    },
    {
        path: "/stardust/transactionhistory/dl/:network/:address",
        method: "post",
        folder: "stardust/transactionhistory/download",
        func: "post",
        dataBody: true,
        dataResponse: true,
    },
    { path: "/stardust/nft/:network/:nftId", method: "get", folder: "stardust/nft", func: "get" },
    { path: "/stardust/alias/:network/:aliasId", method: "get", folder: "stardust/alias", func: "get" },
    {
        path: "/stardust/alias/foundries/:network/:aliasAddress",
        method: "get",
        folder: "stardust/alias/foundries",
        func: "get",
    },
    { path: "/stardust/foundry/:network/:foundryId", method: "get", folder: "stardust/foundry", func: "get" },
    {
        path: "/stardust/analytics/:network",
        method: "get",
        folder: "stardust/analytics/influx/stats",
        func: "get",
        sign: true,
    },
    {
        path: "/stardust/analytics/daily/:network",
        method: "get",
        folder: "stardust/analytics/influx/daily",
        func: "get",
        sign: true,
    },
    {
        path: "/stardust/did/:network/:did/document",
        method: "get",
        folder: "stardust/identity/resolution-stardust",
        func: "get",
    },
    {
        path: "/stardust/participation/events/:network/:eventId",
        method: "get",
        folder: "stardust/participation/events",
        func: "get",
    },
    {
        path: "/stardust/address/rich/:network",
        method: "get",
        folder: "stardust/address/richest",
        func: "get",
    },
    {
        path: "/stardust/token/distribution/:network",
        method: "get",
        folder: "stardust/address/distribution",
        func: "get",
    },
    // Nova
    {
        path: "/nova/balance/chronicle/:network/:address",
        method: "get",
        folder: "nova/address/balance/chronicle",
        func: "get",
    },
    {
        path: "/nova/slot/blocks/chronicle/:network/:slotIndex",
        method: "get",
        folder: "nova/slot/blocks/chronicle",
        func: "get",
    },
    { path: "/nova/search/:network/:query", method: "get", folder: "nova", func: "search" },
    { path: "/nova/output/:network/:outputId", method: "get", folder: "nova/output", func: "get" },
    { path: "/nova/output/rewards/:network/:outputId", method: "get", folder: "nova/output/rewards", func: "get" },
    { path: "/nova/account/:network/:accountId", method: "get", folder: "nova/account", func: "get" },
    { path: "/nova/nft/:network/:nftId", method: "get", folder: "nova/nft", func: "get" },
    { path: "/nova/anchor/:network/:anchorId", method: "get", folder: "nova/anchor", func: "get" },
    { path: "/nova/foundry/:network/:foundryId", method: "get", folder: "nova/foundry", func: "get" },
    {
        path: "/nova/address/outputs/basic/:network/:address",
        method: "get",
        folder: "nova/address/outputs/basic",
        func: "get",
    },
    {
        path: "/nova/address/outputs/nft/:network/:address",
        method: "get",
        folder: "nova/address/outputs/nft",
        func: "get",
    },
    {
        path: "/nova/address/outputs/anchor/:network/:address",
        method: "get",
        folder: "nova/address/outputs/anchor",
        func: "get",
    },
    {
        path: "/nova/address/outputs/delegation/:network/:address",
        method: "get",
        folder: "nova/address/outputs/delegation",
        func: "get",
    },
    {
        path: "/nova/output/associated/:network/:address",
        method: "post",
        folder: "nova/output/associated",
        func: "post",
        dataBody: true,
    },
    {
        path: "/nova/output/delegation/by-validator/:network/:address",
        method: "get",
        folder: "nova/output/delegation/by-validator",
        func: "get",
    },
    {
        path: "/nova/account/foundries/:network/:accountAddress",
        method: "get",
        folder: "nova/account/foundries",
        func: "get",
    },
    {
        path: "/nova/transactionhistory/:network/:address",
        method: "get",
        folder: "nova/transactionhistory",
        func: "get",
    },
    {
        path: "/nova/transaction/:network/:transactionId",
        method: "get",
        folder: "nova/transaction",
        func: "get",
    },
    { path: "/nova/transaction/metadata/:network/:transactionId", method: "get", folder: "nova/transaction/metadata", func: "get" },
    {
        path: "/nova/account/congestion/:network/:accountId",
        method: "get",
        folder: "nova/account/congestion",
        func: "get",
    },
    {
        path: "/nova/account/validator/:network/:accountId",
        method: "get",
        folder: "nova/account/validator",
        func: "get",
    },
    { path: "/nova/block/:network/:blockId", method: "get", folder: "nova/block", func: "get" },
    { path: "/nova/block/metadata/:network/:blockId", method: "get", folder: "nova/block/metadata", func: "get" },
    { path: "/nova/validators/:network", method: "get", folder: "nova/validators", func: "get" },
    { path: "/nova/validators/stats/:network", method: "get", folder: "nova/validators/stats", func: "get" },
    {
        path: "/nova/commitment/latest/:network",
        method: "get",
        folder: "nova/commitment/latest",
        func: "get",
    },
    { path: "/nova/slot/:network/:slotIndex", method: "get", folder: "nova/slot", func: "get" },
    { path: "/nova/epoch/committee/:network/:epochIndex", method: "get", folder: "nova/epoch/committee", func: "get" },
    { path: "/nova/slot/mana-burned/:network/:slotIndex", method: "get", folder: "nova/slot/mana-burned", func: "get" },
    {
        path: "/nova/analytics/:network",
        method: "get",
        folder: "nova/analytics/influx/stats",
        func: "get",
        sign: true,
    },
    {
        path: "/nova/analytics/daily/:network",
        method: "get",
        folder: "nova/analytics/influx/daily",
        func: "get",
        sign: true,
    },
    {
        path: "/nova/output/tagged/:network/:tag/:outputType",
        method: "get",
        folder: "nova/output/tagged",
        func: "get",
    },
    {
        path: "/nova/epoch/stats/:network/:epochIndex",
        method: "get",
        folder: "nova/epoch/influx",
        func: "get",
    },
    {
        path: "/nova/slot/stats/:network/:slotIndex",
        method: "get",
        folder: "nova/slot/blocks/stats",
        func: "get",
    },
];
