blank_issues_enabled: true
contact_links:
  - name: Security vulnerabilities
    url: security@iota.org
    about: Please report security vulnerabilities here.
  - name: General feedback
    url: https://github.com/iotaledger/explorer/discussions/categories/feedback
    about: Leave us some feedback
  - name: Discord
    url: https://discord.iota.org/
    about: Please ask and answer questions here.
