name: Create Draft Release

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version_tag:
        required: true
        type: string

jobs:
  github_draft_release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
            name: ${{ inputs.name }}
            tag_name: ${{ inputs.version_tag }}
            draft: true
