name: Release Explorer to Production

on:
  push:
    tags:
      # Only run workflow on tags that match the semantic versioning pattern 'v1.0.0'
      - ^v(\d+\.\d+\.\d+)$

jobs:
  deploy-production-images:
      name: Deploy Docker Images for Production
      runs-on: ubuntu-latest
      outputs:
        version_tag: ${{ steps.set_version_tag.outputs.version_tag }}
      steps:
        - name: Set up the version tag for docker images
          id: set_version_tag
          run: |
            echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

        - name: Build and push API Docker image
          uses: ./.github/workflows/build-and-push-docker-images.yaml
          with:
            version_tag: ${{ steps.set_version_tag.outputs.version_tag }}
            api_image_tags: |
              iotaledger/explorer-api:${{ steps.set_version_tag.outputs.VERSION_TAG }}
              iotaledger/explorer-api:latest
              iotaledger/explorer-api:latest-stable

            client_image_tags: |
              iotaledger/explorer-client:${{ steps.set_version_tag.outputs.VERSION_TAG }}
              iotaledger/explorer-client:latest
              iotaledger/explorer-client:latest-stable

  deploy_to_server:
    needs: deploy-production-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, shimmer-prod]
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.UPDATER_SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no updater@${{ secrets.EXPLORER_GATEWAY }} "${{ matrix.environment }} ${{ needs.deploy-production-images.outputs.version_tag }}"
